# Generated by Django 5.0.6 on 2024-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('user', 'date')},
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(verbose_name='Период'),
        ),
        migrations.RemoveField(
            model_name='balance',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='date3',
        ),
    ]
