# Generated by Django 5.0.6 on 2024-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_balance_unique_together_alter_balance_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='balance',
            name='date2',
            field=models.DateTimeField(default=1, verbose_name='Период 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='date3',
            field=models.DateTimeField(default=41, verbose_name='Период 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(verbose_name='Период 1'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('user', 'date', 'date2', 'date3')},
        ),
    ]
