# Generated by Django 5.0.6 on 2024-05-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_balance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='period_year',
        ),
    ]
